// This file is auto-generated by @hey-api/openapi-ts

export {helloWorldEndpoint, type Options} from './sdk.gen';
export type {
  ClientOptions,
  ConfluenceDoc,
  HelloWorldEndpointData,
  HelloWorldEndpointResponse,
  HelloWorldEndpointResponses,
} from './types.gen';
