// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type ConfluenceDoc = {
  id: string;
  hash?: null | string;
  type: null | string;
  title: null | string;
  body: null | string;
  space: {
    id: bigint | string;
    key: string;
    name: null | string;
    link: null | string;
  };
  versionNumber: bigint | string;
  versionWhen: Date;
  versionBy: {
    username: null | string;
    userKey: null | string;
    displayName: null | string;
    profilePicturePath: null | string;
  };
  createdDate: Date;
  createdBy: {
    username: null | string;
    userKey: null | string;
    displayName: null | string;
    profilePicturePath: null | string;
  };
  ancestors: Array<{
    id: string;
    type: null | string;
    title: null | string;
    link: null | string;
  }>;
  labels: Array<{
    id: string;
    name: null | string;
    prefix: null | string;
  }>;
  batchIndexDate?: Date;
};

export type HelloWorldEndpointData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api';
};

export type HelloWorldEndpointResponses = {
  /**
   * OK
   */
  200: string;
};

export type HelloWorldEndpointResponse = HelloWorldEndpointResponses[keyof HelloWorldEndpointResponses];
