// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api';
};

export type GetApiResponses = {
  /**
   * OK
   */
  200: string;
};

export type GetApiResponse = GetApiResponses[keyof GetApiResponses];
