// This file is auto-generated by @hey-api/openapi-ts

import {type HttpRequest, httpResource} from '@angular/common/http';

import {client} from '../client.gen';
import type {Options} from '../sdk.gen';
import type {HelloWorldEndpointData, HelloWorldEndpointResponse} from '../types.gen';

/**
 * DERP
 */
export const helloWorldEndpointRequest = <ThrowOnError extends boolean = false>(
  options?: Options<HelloWorldEndpointData, ThrowOnError>,
): HttpRequest<HelloWorldEndpointResponse> =>
  (options?.client ?? client).requestOptions<HelloWorldEndpointResponse, ThrowOnError>({
    responseStyle: 'data',
    method: 'GET',
    url: '/api',
    ...options,
  });

/**
 * DERP
 */
export const helloWorldEndpointResource = <ThrowOnError extends boolean = false>(
  options?: () => Options<HelloWorldEndpointData, ThrowOnError> | undefined,
) =>
  httpResource<HelloWorldEndpointResponse>(() => {
    const opts = options ? options() : undefined;
    return opts ? helloWorldEndpointRequest(opts) : undefined;
  });
