// This file is auto-generated by @hey-api/openapi-ts

export const DseHealthReportSchema = {
  required: ['status', 'totalDuration', 'checks'],
  type: 'object',
  properties: {
    status: {
      type: 'string',
    },
    totalDuration: {
      type: 'string',
    },
    checks: {
      type: 'array',
      items: {
        required: ['name', 'status', 'duration', 'description', 'exception', 'data'],
        type: 'object',
        properties: {
          name: {
            type: 'string',
          },
          status: {
            type: 'string',
          },
          duration: {
            type: 'string',
          },
          description: {
            type: ['null', 'string'],
          },
          exception: {
            type: ['null', 'string'],
          },
          data: {
            type: 'object',
          },
        },
      },
    },
  },
} as const;

export const SourceKeySchema = {
  type: 'string',
} as const;
