// This file is auto-generated by @hey-api/openapi-ts

import type {Client, ClientMeta, Options as Options2, RequestResult, TDataShape} from './client';
import {client} from './client.gen';
import type {
  GetApiTestData,
  GetApiTestResponses,
  GetHealthData,
  GetHealthErrors,
  GetHealthResponses,
  GetHealthSelfData,
  GetHealthSelfErrors,
  GetHealthSelfResponses,
  GetHealthSourcesData,
  GetHealthSourcesErrors,
  GetHealthSourcesResponses,
  GetLiveData,
  GetLiveErrors,
  GetLiveResponses,
  GetReadyData,
  GetReadyErrors,
  GetReadyResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getApiTest = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiTestData, ThrowOnError>,
): RequestResult<GetApiTestResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiTestResponses, unknown, ThrowOnError>({url: '/api/test', ...options});

/**
 * Liveness probe
 *
 * Process is up — no dependency checks run.
 */
export const getLive = <ThrowOnError extends boolean = true>(
  options?: Options<GetLiveData, ThrowOnError>,
): RequestResult<GetLiveResponses, GetLiveErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetLiveResponses, GetLiveErrors, ThrowOnError>({url: '/live', ...options});

/**
 * Readiness probe
 *
 * Process and its ready-tagged dependencies are reachable.
 */
export const getReady = <ThrowOnError extends boolean = true>(
  options?: Options<GetReadyData, ThrowOnError>,
): RequestResult<GetReadyResponses, GetReadyErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetReadyResponses, GetReadyErrors, ThrowOnError>({url: '/ready', ...options});

/**
 * Full health report
 *
 * Every registered check.
 */
export const getHealth = <ThrowOnError extends boolean = true>(
  options?: Options<GetHealthData, ThrowOnError>,
): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({url: '/health', ...options});

/**
 * Source health report
 *
 * Checks tagged 'source'.
 */
export const getHealthSources = <ThrowOnError extends boolean = true>(
  options?: Options<GetHealthSourcesData, ThrowOnError>,
): RequestResult<GetHealthSourcesResponses, GetHealthSourcesErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthSourcesResponses, GetHealthSourcesErrors, ThrowOnError>({
    url: '/health/sources',
    ...options,
  });

/**
 * Health: self
 *
 * The 'self' check in isolation.
 */
export const getHealthSelf = <ThrowOnError extends boolean = true>(
  options?: Options<GetHealthSelfData, ThrowOnError>,
): RequestResult<GetHealthSelfResponses, GetHealthSelfErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthSelfResponses, GetHealthSelfErrors, ThrowOnError>({
    url: '/health/self',
    ...options,
  });
