// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type DseHealthReport = {
  status: string;
  totalDuration: string;
  checks: Array<{
    name: string;
    status: string;
    duration: string;
    description: null | string;
    exception: null | string;
    data: {
      [key: string]: unknown;
    };
  }>;
};

export type SourceKey = string;

export type GetApiTestData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/test';
};

export type GetApiTestResponses = {
  /**
   * OK
   */
  200: SourceKey;
};

export type GetApiTestResponse = GetApiTestResponses[keyof GetApiTestResponses];

export type GetLiveData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/live';
};

export type GetLiveErrors = {
  /**
   * Unhealthy
   */
  503: string;
};

export type GetLiveError = GetLiveErrors[keyof GetLiveErrors];

export type GetLiveResponses = {
  /**
   * Healthy or Degraded
   */
  200: string;
};

export type GetLiveResponse = GetLiveResponses[keyof GetLiveResponses];

export type GetReadyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/ready';
};

export type GetReadyErrors = {
  /**
   * Unhealthy
   */
  503: string;
};

export type GetReadyError = GetReadyErrors[keyof GetReadyErrors];

export type GetReadyResponses = {
  /**
   * Healthy or Degraded
   */
  200: string;
};

export type GetReadyResponse = GetReadyResponses[keyof GetReadyResponses];

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type GetHealthErrors = {
  /**
   * Unhealthy
   */
  503: DseHealthReport;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
  /**
   * Healthy or Degraded
   */
  200: DseHealthReport;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetHealthSourcesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health/sources';
};

export type GetHealthSourcesErrors = {
  /**
   * Unhealthy
   */
  503: DseHealthReport;
};

export type GetHealthSourcesError = GetHealthSourcesErrors[keyof GetHealthSourcesErrors];

export type GetHealthSourcesResponses = {
  /**
   * Healthy or Degraded
   */
  200: DseHealthReport;
};

export type GetHealthSourcesResponse = GetHealthSourcesResponses[keyof GetHealthSourcesResponses];

export type GetHealthSelfData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health/self';
};

export type GetHealthSelfErrors = {
  /**
   * Unhealthy
   */
  503: DseHealthReport;
};

export type GetHealthSelfError = GetHealthSelfErrors[keyof GetHealthSelfErrors];

export type GetHealthSelfResponses = {
  /**
   * Healthy or Degraded
   */
  200: DseHealthReport;
};

export type GetHealthSelfResponse = GetHealthSelfResponses[keyof GetHealthSelfResponses];
