// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zDseHealthReport = z.object({
  status: z.string(),
  totalDuration: z.string(),
  checks: z.array(
    z.object({
      name: z.string(),
      status: z.string(),
      duration: z.string(),
      description: z.string().nullable(),
      exception: z.string().nullable(),
      data: z.record(z.string(), z.unknown()),
    }),
  ),
});

export const zSourceKey = z.string();

/**
 * OK
 */
export const zGetApiTestResponse = zSourceKey;

/**
 * Healthy or Degraded
 */
export const zGetLiveResponse = z.string();

/**
 * Healthy or Degraded
 */
export const zGetReadyResponse = z.string();

/**
 * Healthy or Degraded
 */
export const zGetHealthResponse = zDseHealthReport;

/**
 * Healthy or Degraded
 */
export const zGetHealthSourcesResponse = zDseHealthReport;

/**
 * Healthy or Degraded
 */
export const zGetHealthSelfResponse = zDseHealthReport;
