#!/usr/bin/env node
// Pins the SonarQube "Sonar way PNC" TypeScript profile onto eslint-plugin-sonarjs.
// Reads Sonar-way-PNC-ts.xml + the installed plugin's own rule metadata (which carries
// the RSPEC S-key in meta.docs.url) to map each S#### -> sonarjs/<rule-name>, then emits
// eng/sonar/sonarjs-pnc-rules.mjs (a flat-config `rules` object) consumed by eslint.config.ts.
//
// Re-export the profile from the server and re-run `node eng/sonar/convert-ts.mjs` to refresh.
//
// Severity (graded, mirrors the C# side): BLOCKER/CRITICAL/MAJOR -> 'error'; MINOR/INFO -> 'warn'.

import sonarjs from 'eslint-plugin-sonarjs';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const xml = readFileSync(join(here, 'Sonar-way-PNC-ts.xml'), 'utf8');

// S-key -> sonarjs rule name, derived from the plugin itself (authoritative, not guessed).
const keyToRule = {};
for (const [name, rule] of Object.entries(sonarjs.rules ?? {})) {
  const m = (rule.meta?.docs?.url ?? '').match(/rspec\/(S\d+)\//);
  if (m) keyToRule[m[1]] ??= name;
}

const SEVERITY = { BLOCKER: 'error', CRITICAL: 'error', MAJOR: 'error', MINOR: 'warn', INFO: 'warn' };

// Only rules whose PNC parameter differs from the plugin default need explicit options.
// (Verified: every other parameterized PNC rule matches the plugin's defaultOptions.)
const PARAM_OVERRIDES = {
  S101: (sev) => [sev, { format: '^[A-Z][a-zA-Z0-9]*$' }], // PNC forbids the leading "$" the default allows
};

const rules = [...xml.matchAll(/<rule>([\s\S]*?)<\/rule>/g)].map(([, body]) => ({
  repo: (body.match(/<repositoryKey>([^<]*)<\/repositoryKey>/) ?? [, ''])[1],
  key: (body.match(/<key>([^<]*)<\/key>/) ?? [, ''])[1],
  priority: (body.match(/<priority>([^<]*)<\/priority>/) ?? [, ''])[1],
  hasParams: /<parameter>/.test(body),
}));

const tsRules = rules.filter((r) => r.repo === 'typescript');
const serverOnly = rules.filter((r) => r.repo === 'tssecurity' || r.repo === 'tsarchitecture');

const out = {};
const mapped = [];
const unmapped = [];
const paramAtDefault = [];
for (const r of tsRules) {
  const name = keyToRule[r.key];
  const sev = SEVERITY[r.priority];
  if (!sev) throw new Error(`Unmapped priority "${r.priority}" on ${r.key}`);
  if (!name) { unmapped.push(r.key); continue; }
  out[`sonarjs/${name}`] = PARAM_OVERRIDES[r.key] ? PARAM_OVERRIDES[r.key](sev) : sev;
  mapped.push(r.key);
  if (r.hasParams && !PARAM_OVERRIDES[r.key]) paramAtDefault.push(r.key);
}

const banner =
  `// GENERATED by eng/sonar/convert-ts.mjs — do not edit by hand.\n` +
  `// SonarQube profile "Sonar way PNC" (ts) pinned onto eslint-plugin-sonarjs.\n` +
  `// ${mapped.length} rules enforced. ${unmapped.length} profile rules are not in the plugin\n` +
  `// (newer S-rules or rules SonarQube sources from other engines) — see convert-ts.mjs output.\n` +
  `// ${serverOnly.length} tssecurity/tsarchitecture rules are server-only (taint/architecture) and cannot run offline.\n`;
const file = `${banner}export const sonarjsPncRules = ${JSON.stringify(sortKeys(out), null, 2)};\n`;
writeFileSync(join(here, 'sonarjs-pnc-rules.mjs'), file);

function sortKeys(o) {
  return Object.fromEntries(Object.keys(o).sort().map((k) => [k, o[k]]));
}

console.log(`Profile "Sonar way PNC" (ts):`);
console.log(`  plugin exposes ${Object.keys(keyToRule).length} S-keyed rules`);
console.log(`  ${mapped.length} PNC rules pinned -> sonarjs-pnc-rules.mjs`);
console.log(`  ${paramAtDefault.length} parameterized rules use plugin defaults (match PNC): ${paramAtDefault.join(', ')}`);
console.log(`  ${Object.keys(PARAM_OVERRIDES).filter((k) => mapped.includes(k)).length} parameterized rules overridden: ${Object.keys(PARAM_OVERRIDES).filter((k) => mapped.includes(k)).join(', ')}`);
console.log(`  ${unmapped.length} PNC rules NOT in plugin (skipped): ${unmapped.join(', ')}`);
console.log(`  ${serverOnly.length} server-only (tssecurity/tsarchitecture): ${serverOnly.map((r) => r.key).join(', ')}`);
