#!/usr/bin/env node
// Converts a SonarQube C# Quality Profile backup (XML) into the offline artifacts
// the SonarAnalyzer.CSharp Roslyn analyzer consumes:
//   - sonar-quality-profile.globalconfig : per-rule severities (graded, build-breaking)
//   - SonarLint.xml                      : parameter values for parameterized rules
//
// Re-export the profile from the server (Quality Profiles > Back up) over the top of
// Sonar-way-PNC.xml and re-run `node eng/sonar/convert.mjs` to regenerate. Nothing here
// is hand-maintained.
//
// Severity policy (decided: graded, build-breaking on high severity):
//   BLOCKER | CRITICAL | MAJOR -> warning   (=> build error via TreatWarningsAsErrors)
//   MINOR   | INFO            -> suggestion  (IDE hint only, never breaks the build)

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const srcPath = process.argv[2] ?? join(here, 'Sonar-way-PNC.xml');
const xml = readFileSync(srcPath, 'utf8');

// SonarAnalyzer.CSharp ships these rules in the free Roslyn NuGet.
const NUGET_REPO = 'csharpsquid';
// SonarSecurity taint analysis (Developer Edition+) — server-side only, not in the NuGet.
const SERVER_ONLY_REPO = 'roslyn.sonaranalyzer.security.cs';

const SEVERITY = { BLOCKER: 'warning', CRITICAL: 'warning', MAJOR: 'warning', MINOR: 'suggestion', INFO: 'suggestion' };

const profileName = (xml.match(/<name>([^<]*)<\/name>/) ?? [, 'unknown'])[1];

const rules = [...xml.matchAll(/<rule>([\s\S]*?)<\/rule>/g)].map(([, body]) => {
  const pick = (tag) => (body.match(new RegExp(`<${tag}>([^<]*)</${tag}>`)) ?? [, ''])[1];
  const params = [...body.matchAll(/<parameter><key>([^<]*)<\/key><value>([\s\S]*?)<\/value><\/parameter>/g)]
    .map(([, key, value]) => ({ key, value }));
  return { repo: pick('repositoryKey'), key: pick('key'), priority: pick('priority'), params };
});

const byNum = (a, b) => Number(a.key.slice(1)) - Number(b.key.slice(1));
const active = rules.filter((r) => r.repo === NUGET_REPO).sort(byNum);
const serverOnly = rules.filter((r) => r.repo === SERVER_ONLY_REPO).sort(byNum);
const other = rules.filter((r) => r.repo !== NUGET_REPO && r.repo !== SERVER_ONLY_REPO);

const xmlEscape = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// --- sonar-quality-profile.globalconfig ----------------------------------------------
const gc = [];
gc.push('# GENERATED by eng/sonar/convert.mjs — do not edit by hand.');
gc.push(`# Source: SonarQube quality profile "${profileName}" (language: cs).`);
gc.push('# Severities: BLOCKER/CRITICAL/MAJOR -> warning (build error via TreatWarningsAsErrors); MINOR/INFO -> suggestion.');
gc.push('is_global = true');
gc.push('');
for (const r of active) {
  const sev = SEVERITY[r.priority];
  if (!sev) throw new Error(`Unmapped priority "${r.priority}" on ${r.key}`);
  gc.push(`dotnet_diagnostic.${r.key}.severity = ${sev}   # ${r.priority}`);
}
gc.push('');
gc.push(`# ${serverOnly.length} SonarSecurity taint-analysis rules in this profile run SERVER-SIDE ONLY`);
gc.push('# (repo roslyn.sonaranalyzer.security.cs, Developer Edition+). They are NOT in the free');
gc.push('# SonarAnalyzer.CSharp NuGet and cannot be enforced offline — listed here for the record:');
for (const r of serverOnly) gc.push(`#   ${r.key} (${r.priority})`);
writeFileSync(join(here, 'sonar-quality-profile.globalconfig'), gc.join('\n') + '\n');

// --- SonarLint.xml (parameterized active rules only) ---------------------------------
const parameterized = active.filter((r) => r.params.length > 0);
const sl = [];
sl.push('<?xml version="1.0" encoding="UTF-8"?>');
sl.push('<!-- GENERATED by eng/sonar/convert.mjs — do not edit by hand. -->');
sl.push('<AnalysisInput>');
sl.push('  <Rules>');
for (const r of parameterized) {
  sl.push('    <Rule>');
  sl.push(`      <Key>${r.key}</Key>`);
  sl.push('      <Parameters>');
  for (const p of r.params) {
    sl.push(`        <Parameter><Key>${xmlEscape(p.key)}</Key><Value>${xmlEscape(p.value)}</Value></Parameter>`);
  }
  sl.push('      </Parameters>');
  sl.push('    </Rule>');
}
sl.push('  </Rules>');
sl.push('</AnalysisInput>');
writeFileSync(join(here, 'SonarLint.xml'), sl.join('\n') + '\n');

if (other.length) {
  console.warn(`WARNING: ${other.length} rules from unexpected repositories were ignored:`,
    [...new Set(other.map((r) => r.repo))].join(', '));
}
console.log(`Profile "${profileName}":`);
console.log(`  ${active.length} enforceable rules  -> sonar-quality-profile.globalconfig`);
console.log(`  ${parameterized.length} parameterized rules -> SonarLint.xml`);
console.log(`  ${serverOnly.length} server-only rules  -> documented (not enforceable offline)`);
